export const offers = [
  {
    title: "Reseller",
    price: 500,
    amplifier: "rb",
    discount: 20,
    descriptions: [
      "Diskon 20% ",
      "Min. repeat order 2pcs",
      "Pelatihan setiap minggu",
      "Dibimbing oleh tim pusat SR12",
      "Produk sudah tersertifikasi",
      "Mendapat ID Card Resmi",
      "Produk menjakau usia 15-60thn",
      "Produk cocok untuk semua kulit",
      "Konten Marketing/promosi",
      "Harga jual terjamin",
    ],
    url: "https://api.whatsapp.com/send/?phone=6281332767575",
    recommended: false,
  },
  {
    title: "Sub Agen",
    price: 5,
    amplifier: "jt",
    discount: 30,
    descriptions: [
      "Diskon 30%",
      "Min. repeat order 1 jt",
      "Pelatihan setiap minggu",
      "Dibimbing oleh tim pusat SR12",
      "Produk sudah tersertifikasi",
      "Mendapat ID Card Resmi",
      "Produk menjakau usia 15-60thn",
      "Produk cocok untuk semua kulit",
      "Konten Marketing/promosi",
      "Harga jual terjamin",
    ],
    url: "https://api.whatsapp.com/send/?phone=6281332767575",
    recommended: true,
  },
  {
    title: "Agen",
    price: 25,
    amplifier: "jt",
    discount: 40,
    descriptions: [
      "Diskon 40%",
      "Min. repeat order 2 jt",
      "Pelatihan setiap minggu",
      "Dibimbing oleh tim pusat SR12",
      "Produk sudah tersertifikasi",
      "Mendapat ID Card Resmi",
      "Produk menjakau usia 15-60thn",
      "Produk cocok untuk semua kulit",
      "Konten Marketing/promosi",
      "Harga jual terjamin ",
    ],
    url: "https://api.whatsapp.com/send/?phone=6281332767575",
    recommended: false,
  },
];
